### ISSUE TITLE
Fix: name 'show_warning' is not defined

### ISSUE THREAD

**Issue by anjackson** [anjackson/ipywardley#2]
Well, `name 'show_warning' is not defined` at:

```
 for n in edge:
                     if n not in wm.nodes:
                         show_warning("Could not find a component called '%s'!" % n)
```

**Comment by RonaldAJ** [comment]
Show_warning lacks the first argument.

**Comment by RonaldAJ** [comment]
Note: Can be tested with adding something like A->B to an arbitrary map and watching the output.

**Comment by anjackson** [comment]
Thanks @RonaldAJ that fix looks good.
